replicaCount: 2

image:
  repository: yandex/clickhouse-server
  tag: 21.3.20

users:
  - name: admin
    password: admin

initsql: {}

resources:
  limits:
    cpu: 125m
    memory: 256Mi
  requests:
    cpu: 125m
    memory: 256Mi

persistence:
  mountPath: /var/lib/clickhouse
  accessModes:
    - ReadWriteOnce
  size: 1Gi

nodeSelector: {}

affinity: {}

tolerations: []

# deploys clickhouse-client
client:
  enabled: true

# zookeeper
zookeeper:
  auth:
    enabled: true
    clientUser: zookeeper
    clientPassword: zookeeperpassword
    serverUsers: clickhouse
    serverPasswords: clickhouse
  replicaCount: 2
  persistence:
    size: 1Gi
  nodeSelector: {}

metrics:
  enabled: false

  image:
    registry: docker.io
    repository: flant/clickhouse-exporter
    tag: 0.2.1
    pullPolicy: IfNotPresent
    pullSecrets: []

  resources:
    limits: {}
    requests: {}

  service:
    type: ClusterIP
    port: 9116

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9116"
