{{ $key := default (randAlphaNum 10) .Values.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forwarder.fullname" . }}
type: Opaque
data:
  APP_ALERTMANAGER_SECRET: {{ default (randAlphaNum 10) .Values.key | b64enc }}
  MATRIX_HOMESERVER_URL: {{ include "forwarder.homeserver" .  | b64enc }}
  MATRIX_ROOMS: {{ .Values.matrix.roomID | b64enc }}
  MATRIX_PASSWORD:  {{ .Values.matrix.password | b64enc }}
  MATRIX_USER: {{ .Values.matrix.user | b64enc }}
  MENTION_ROOM: {{ "0" | b64enc }}
