apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "clickhouse.fullname" .) }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9000
    name: rpc
  - port: 8123
    name: rest
  - port: 9009
    name: interserver
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4}}